import { Metadata } from "next";
import React from "react";

type LayoutProps = {
  children: React.ReactNode;
  products: React.ReactNode;
  analytics: React.ReactNode;
  payments: React.ReactNode;
};

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };

export default function Layout({ children, products, analytics }: LayoutProps) {
  return (
    <div className="p-5">
      <div>{children}</div>
      <div className="mt-5 flex justify-center items-center gap-5">
        {products}
        {analytics}
      </div>
      {/* {payments} */}
    </div>
  );
}
